### PR TITLE
Weather app 

### PR DESCRIPTION
**Pull request by ashraffares**
- using fetch to make an API call to get the weather data.
- addinfo method to add content to HTML using DOM.
- getinput method to addEeventLiestnere and trigger the API call.
- used Webpack assets management.

### CODE REVIEW

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [ ] PR title and summary are descriptive.
- [ ] README includes all the steps to run the project locally.
## To Improve 🙏
- [x] `webpack` should be added in devDependencies of the project. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/devdep_requirement.png).
- [x] `scripts` should include `"dev": "webpack --mode development"`. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/scripts_requirement.png).
- [x] App does not show any weather data when user tries to search a location. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png).
- [x] App should have a toggle button which allows a user to convert Celsius to Farenheit and vice versa. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png).
- [ ] App should change its appearance based on the received data. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png).
- [x] Please use different modules and do not put all of the code in one file. For example, there can be one module for data fetch from API and one for showing it on screen. 
# Optional
- [x] Deploy app on Heroku or Netlify and add a live link in README.
- [x] App may fetch the current geolocation of the user when it is first accessed and fetches the weather from that location
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - Follows gitwork-flow.  💯
  - Codebase looks clean and professional. 💯 


- ### To Improve

  As the previous reveiwer requested,
  - [ ] [MANDATORY] App should have a toggle button which allows a user to convert Celsius to Farenheit and vice versa. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png).
  - [ ] [MANDATORY] App should change its appearance based on the received data. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png).

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Comment by ashraffares** [comment]
https://www.loom.com/share/acd119856c2f487698690dc2937fc840

**Comment by ashraffares** [comment]
please watch the video before reviewing the project
https://www.loom.com/share/acd119856c2f487698690dc2937fc840
- to toggle between C and F you need to click on it and you will find it hoverable.
-  image change depending on the weather so if the weather changes the image will change.

**Review by SajjadAhmad14 — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Pull request merged**
